### ISSUE TITLE
URL invalid

### ISSUE THREAD

**Issue by yiwenchen1999** [liuzhengzhe/Towards-Implicit-Text-Guided-Shape-Generation#1]
Hi, I think the URL for the pretrained model and data [hdf5_train_new](https://github.com/liuzhengzhe/Towards-Implicit-Text-Guided-Shape-Generation/blob/main) and [hdf5_test_new](https://github.com/liuzhengzhe/Towards-Implicit-Text-Guided-Shape-Generation/blob/main) are invalid, I keep getting 404 pages.

**Comment by smagnan** [comment]
Same issue with the model itself. Fr om looking at the Readme markdown, it seems like the urls are missing for train, test and model so we get redirected to https://github.com/liuzhengzhe/Towards-Implicit-Text-Guided-Shape-Generation/blob/main resulting in a 404

**Comment by liuzhengzhe** [comment]
Hi, I have just uploaded the data and model. Please check it.

Regards,
Zhengzhe

Samuel MAGNAN ***@***.***> 于2022年4月13日周三 07:07写道：

**Comment by smagnan** [comment]
Thanks, perfect! Looking forward to testing out the model

**Comment by yiwenchen1999** [comment]
Thanks!
