### ISSUE TITLE
Code to compute the metrics

### ISSUE THREAD

**Issue by AndreAmaduzzi** [liuzhengzhe/Towards-Implicit-Text-Guided-Shape-Generation#3]
Good morning,
I am currently trying to replicate your results, in terms of the metrics IoU, Inception Score, EMD and Classification Accuracy.
For repeatibility reasons, I would like to access the code you have used to compute these metrics.
So far, I have not been able to find it in your repository.
Therefore, I would like to know if you are going to release this code.

Thanks,
Andrea

**Comment by liuzhengzhe** [comment]
Hi, I have updated the google drive link. See README.md.

Zhengzhe

**Comment by AndreAmaduzzi** [comment]
Thanks.
