### ISSUE TITLE
Details on calculating FPD 

### ISSUE THREAD

**Issue by WayneCV** [liuzhengzhe/Towards-Implicit-Text-Guided-Shape-Generation#7]
Hi, could you share more details on FPD (e.g., the newly-trained PointNet pre-train model)? I think sharing it is necessary for post works conducting fair comparisons. Thanks in advance.

**Comment by liuzhengzhe** [comment]
Hi, I have updated the google drive link. See README.md.

Zhengzhe

**Comment by WayneCV** [comment]
> Hi, I have updated the google drive link. See README.md.
> 
> Zhengzhe

Thanks!
